package ast

import "glox/internal"
import "fmt"

// WARNING: autogenerated file. Do not modify this file, other than to format.

type ExprVisitor struct {
	VisitBinary   func(Binary)
	VisitGrouping func(Grouping)
	VisitLiteral  func(Literal)
	VisitUnary    func(Unary)
}

type Expr interface {
	Visit(v ExprVisitor)
}
type Binary struct {
	Left     Expr
	Operator internal.Token
	Right    Expr
}

func (e Binary) Visit(v ExprVisitor) {
	v.VisitBinary(e)
}

type Grouping struct {
	Expression Expr
}

func (e Grouping) Visit(v ExprVisitor) {
	v.VisitGrouping(e)
}

type Literal struct {
	Value fmt.Stringer
}

func (e Literal) Visit(v ExprVisitor) {
	v.VisitLiteral(e)
}

type Unary struct {
	Operator internal.Token
	Right    Expr
}

func (e Unary) Visit(v ExprVisitor) {
	v.VisitUnary(e)
}
