package internal

// WARNING: autogenerated file. Do not modify this file, other than to format.

type ExprVisitor struct {
	VisitBinary   func(Binary)
	VisitGrouping func(Grouping)
	VisitLiteral  func(Literal)
	VisitUnary    func(Unary)
}

type Expr interface {
	Visit(v ExprVisitor)
}
type Binary struct {
	Left     Expr
	Operator Token
	Right    Expr
}

type Grouping struct {
	Expression Expr
}

type Literal struct {
	Value interface{}
}

type Unary struct {
	Operator Token
	Right    Expr
}
