package internal

import "fmt"

// WARNING: autogenerated file. Do not modify this file, other than to format.

type ExprVisitor struct {
	VisitBinary   func(Binary) interface{}
	VisitGrouping func(Grouping) interface{}
	VisitLiteral  func(Literal) interface{}
	VisitUnary    func(Unary) interface{}
	VisitTernary  func(Ternary) interface{}
}

type Expr interface {
	Visit(v ExprVisitor) interface{}
}
type Binary struct {
	Left     Expr
	Operator Token
	Right    Expr
}

func (e Binary) Visit(v ExprVisitor) interface{} {
	return v.VisitBinary(e)
}

type Grouping struct {
	Expression Expr
}

func (e Grouping) Visit(v ExprVisitor) interface{} {
	return v.VisitGrouping(e)
}

type Literal struct {
	Value fmt.Stringer
}

func (e Literal) Visit(v ExprVisitor) interface{} {
	return v.VisitLiteral(e)
}

type Unary struct {
	Operator Token
	Right    Expr
}

func (e Unary) Visit(v ExprVisitor) interface{} {
	return v.VisitUnary(e)
}

type Ternary struct {
	Cond        Expr
	TrueBranch  Expr
	FalseBranch Expr
}

func (e Ternary) Visit(v ExprVisitor) interface{} {
	return v.VisitTernary(e)
}
